### ISSUE TITLE
Maintaining the equality of areas?

### ISSUE THREAD

**Issue by zvezdochiot** [Ambrevar/perspector#1]
Hi @Ambrevar .

:question: Interested in converting the image of (WxH) to (WxH), subject to the equality `area(1,2,3,4) == area (w, h)`. See https://github.com/ImageProcessing-ElectronicPublications/page_dewarp/blob/master/page_depersp.py

![depersp](https://svgshare.com/i/LPJ.svg)

**Comment by Ambrevar** [comment]
Hi!  I'm sorry, I don't understand your question.

**Comment by zvezdochiot** [comment]
Hi @Ambrevar .

I will clarify the details:

1. The resulting image is the same size as the input image (in the first stage, it is better to simply copy it).
2. The area of the quadrilateral (1,2,3,4) is equal to the area of the resulting rectangle (w, h).
3. The entire image undergoes transformation (missing pixels remain original, see 1, those that go beyond the borders are truncated).

**Comment by Ambrevar** [comment]
What are you trying to do and what is your question?

**Comment by zvezdochiot** [comment]
I am trying to fix scanned pages with bends. But so as to maintain scale (very important for the book).

**Comment by Ambrevar** [comment]
Are you sure you want to "maintain" the scale?  Because when you fix the
perspective by definition you change the scale.

Maybe you want to obtain a specific scale instead.

**Comment by zvezdochiot** [comment]
Hi @Ambrevar .

No. The equality of the areas of the quadrangle and the resulting rectangle is required.

**Comment by zvezdochiot** [comment]
https://github.com/ImageProcessing-ElectronicPublications/perspector/commit/001f2001587c59fe8d1bb3113a8e5e8c6d0c8cfb

![isometric](https://i112.fastpic.ru/big/2020/0528/89/5dadb5e808b4baa7bb324207981f7889.jpg)

**Comment by Ambrevar** [comment]
What about this picture?

**Comment by zvezdochiot** [comment]
@Ambrevar say:
>What about this picture?

What?

**Comment by zvezdochiot** [comment]
@Ambrevar say:
>I'm not working on this project

:cry: Very sorry.
