### ISSUE TITLE
TODO: Shift viewport?

### ISSUE THREAD

**Issue by zvezdochiot** [Ambrevar/perspector#3]
Hi @Ambrevar .

:question: My knowledge is not enough to adjust the shift of the viewing area with the increase. Maybe you help me?

**Comment by Ambrevar** [comment]
What's the viewing area?
Shift how?
What's the "increase"?

**Comment by zvezdochiot** [comment]
@Ambrevar say:
>What's the viewing area?

The part of the image that fits in the window.

@Ambrevar say:
>Shift how?

Right and down.

@Ambrevar say:
>What's the "increase"?

Zoom.

**Comment by Ambrevar** [comment]
I'm not working on this project (which is more of a toy project) but
if you are interested and know a bit of C, feel free to send a patch,
I'll be happy to merge! :)

**Comment by zvezdochiot** [comment]
@Ambrevar say:
>I'm not working on this project

:cry: Very sorry.
